[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  framework = "#custom"
  targetPort = 5000
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
